# Generated by Django 4.0.4 on 2022-06-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='friday_end',
            field=models.TimeField(db_column='FridayEnd', null=True, verbose_name='Friday End'),
        ),
        migrations.AlterField(
            model_name='park',
            name='friday_start',
            field=models.TimeField(db_column='FridayStart', null=True, verbose_name='Friday Start'),
        ),
        migrations.AlterField(
            model_name='park',
            name='monday_end',
            field=models.TimeField(db_column='MondayEnd', null=True, verbose_name='Monday End'),
        ),
        migrations.AlterField(
            model_name='park',
            name='monday_start',
            field=models.TimeField(db_column='MondayStart', null=True, verbose_name='Monday Start'),
        ),
        migrations.AlterField(
            model_name='park',
            name='saturday_end',
            field=models.TimeField(db_column='SaturdayEnd', null=True, verbose_name='Saturday End'),
        ),
        migrations.AlterField(
            model_name='park',
            name='saturday_start',
            field=models.TimeField(db_column='SaturdayStart', null=True, verbose_name='Saturday Start'),
        ),
        migrations.AlterField(
            model_name='park',
            name='sunday_end',
            field=models.TimeField(db_column='SundayEnd', null=True, verbose_name='Sunday End'),
        ),
        migrations.AlterField(
            model_name='park',
            name='sunday_start',
            field=models.TimeField(db_column='SundayStart', null=True, verbose_name='Sunday Start'),
        ),
        migrations.AlterField(
            model_name='park',
            name='thursday_end',
            field=models.TimeField(db_column='ThursdayEnd', null=True, verbose_name='Thursday End'),
        ),
        migrations.AlterField(
            model_name='park',
            name='thursday_start',
            field=models.TimeField(db_column='ThursdayStart', null=True, verbose_name='Thursday Start'),
        ),
        migrations.AlterField(
            model_name='park',
            name='tuesday_end',
            field=models.TimeField(db_column='TuesdayEnd', null=True, verbose_name='Tuesday End'),
        ),
        migrations.AlterField(
            model_name='park',
            name='tuesday_start',
            field=models.TimeField(db_column='TuesdayStart', null=True, verbose_name='Tuesday Start'),
        ),
        migrations.AlterField(
            model_name='park',
            name='wednesday_end',
            field=models.TimeField(db_column='WednesdayEnd', null=True, verbose_name='Wednesday End'),
        ),
        migrations.AlterField(
            model_name='park',
            name='wednesday_start',
            field=models.TimeField(db_column='WednesdayStart', null=True, verbose_name='Wednesday Start'),
        ),
    ]
