# Generated by Django 4.0.4 on 2022-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0004_parkingspot_direction_parkingspot_x_parkingspot_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.IntegerField(db_column='Number', max_length=3, verbose_name='Number'),
        ),
    ]
