# Generated by Django 4.0.4 on 2022-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0005_alter_parkingspot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.IntegerField(db_column='Number', verbose_name='Number'),
        ),
    ]
