# Generated by Django 4.0.4 on 2022-06-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0006_alter_parkingspot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCodeCity',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True, verbose_name='Name')),
                ('postal_code', models.IntegerField(db_column='PostalCode', max_length=4, unique=True, verbose_name='Postal Code')),
            ],
        ),
    ]
