# Generated by Django 4.0.4 on 2022-06-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0007_postalcodecity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostalCodeCity',
        ),
    ]
