# Generated by Django 4.0.4 on 2022-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0008_delete_postalcodecity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='hours',
            field=models.IntegerField(db_column='HoursTime', default=1, verbose_name='Hours Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricetype',
            name='minutes',
            field=models.IntegerField(db_column='MinutesTime', default=1, verbose_name='Minutes Time'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together={('minutes', 'hours', 'park')},
        ),
        migrations.RemoveField(
            model_name='pricetype',
            name='time',
        ),
    ]
