# Generated by Django 4.0.4 on 2022-06-08 18:54

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0009_alter_pricetype_unique_together_pricetype_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetype',
            name='hours',
            field=models.IntegerField(db_column='HoursTime', default=0, verbose_name='Hours Time'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='minutes',
            field=models.IntegerField(db_column='MinutesTime', default=0, verbose_name='Minutes Time'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=14),
        ),
    ]
