# Generated by Django 4.0.4 on 2022-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0010_alter_pricetype_hours_alter_pricetype_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='total_currency',
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='total',
            field=models.DecimalField(db_column='TotalValue', decimal_places=2, default=0, max_digits=6, verbose_name='Total Value'),
        ),
    ]
