# Generated by Django 4.0.4 on 2022-06-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0011_remove_pricetype_total_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttype',
            name='time',
        ),
        migrations.AddField(
            model_name='contracttype',
            name='months',
            field=models.IntegerField(db_column='MonthsTime', default=0, verbose_name='Months Time'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='years',
            field=models.IntegerField(db_column='YearsTime', default=0, verbose_name='Years Time'),
        ),
    ]
