# Generated by Django 4.0.6 on 2022-07-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contrato_userid_alter_reserva_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='parqueid',
            field=models.ForeignKey(blank=True, db_column='ParqueID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.park'),
        ),
    ]
