# Generated by Django 4.0.6 on 2022-07-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reserva_parqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='matricula',
            field=models.CharField(db_column='Matricula', default=1, max_length=8, verbose_name='Matricula'),
            preserve_default=False,
        ),
    ]
