# Generated by Django 4.0.4 on 2022-07-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_park_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='typology',
            field=models.CharField(db_column='Typology', max_length=50, verbose_name='Typology'),
        ),
    ]
