# Generated by Django 4.0.4 on 2022-07-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_park_typology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='city',
            field=models.CharField(db_column='City', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='park',
            name='typology',
            field=models.CharField(choices=[('ST', 'Structure'), ('SF', 'Surface')], db_column='Typology', max_length=2, verbose_name='Typology'),
        ),
    ]
