# Generated by Django 4.0.4 on 2022-07-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_park_city_alter_park_typology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='foreign',
            field=models.BooleanField(db_column='Is Foreign', verbose_name='Is Foreign'),
        ),
    ]
