# Generated by Django 4.0.4 on 2022-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_car_foreign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.CharField(db_column='Registration', max_length=8, verbose_name='Registration'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('registration', 'foreign')},
        ),
    ]
