# Generated by Django 4.0.4 on 2022-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_car_brand_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deleted',
            field=models.BooleanField(db_column='Deleted', default=False, verbose_name='Is Deleted'),
        ),
    ]
