# Generated by Django 4.0.4 on 2022-07-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_car_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='direction',
            field=models.CharField(choices=[('VE', 'Vertical'), ('HO', 'Horizontal')], db_column='Direction', max_length=2, verbose_name='Direction'),
        ),
    ]
