# Generated by Django 4.0.4 on 2022-07-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_parkingspot_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='parqueid',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estadoreservaid',
            field=models.ForeignKey(db_column='EstadoReservaID', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.estadoreserva'),
        ),
    ]
