# Generated by Django 4.0.4 on 2022-07-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_reserva_parqueid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='parqueid',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='zonaid',
        ),
        migrations.AddField(
            model_name='contrato',
            name='lugarid',
            field=models.ForeignKey(db_column='LugarID', default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='main.parkingspot'),
            preserve_default=False,
        ),
    ]
