# Generated by Django 4.0.4 on 2022-07-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contrato_datafim_contrato_estadoreservaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='modalidadepagamentoid',
            field=models.ForeignKey(blank=True, db_column='ModalidadePagamentoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.modalidadepagamento'),
        ),
    ]
