# Generated by Django 4.0.4 on 2022-07-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contrato_modalidadepagamentoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='datavalidade',
        ),
    ]
