# Generated by Django 4.0.4 on 2022-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_contrato_datavalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valorcontrato',
            field=models.FloatField(blank=True, db_column='ValorContrato', null=True),
        ),
    ]
