# Generated by Django 4.0.4 on 2022-07-05 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_contrato_valorcontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='criadoem',
            field=models.DateTimeField(db_column='CriadoEm', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='editadoem',
            field=models.DateTimeField(db_column='EditadoEm', default=django.utils.timezone.now),
        ),
    ]
