# Generated by Django 4.0.6 on 2022-07-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_pricetype_is_fine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractType',
        ),
    ]
