# Generated by Django 4.0.6 on 2022-07-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_contracttype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together={('minutes', 'hours', 'park', 'is_fine')},
        ),
    ]
