# Generated by Django 4.0.6 on 2022-07-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_pricetype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='type',
            field=models.CharField(choices=[('NO', 'Normal'), ('FI', 'Fine')], db_column='Type', default=1, max_length=2, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together={('minutes', 'hours', 'park', 'type')},
        ),
        migrations.RemoveField(
            model_name='pricetype',
            name='is_fine',
        ),
    ]
