# Generated by Django 4.0.6 on 2022-07-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_pricetype_unique_together_pricetype_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='deadline',
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('arquived', models.BooleanField(db_column='Arquived', default=False, verbose_name='Arquived')),
                ('deadline', models.OneToOneField(db_column='Deadline', on_delete=django.db.models.deletion.CASCADE, to='main.dateperiod', verbose_name='Deadline')),
                ('park', models.ForeignKey(db_column='Parque', on_delete=django.db.models.deletion.CASCADE, to='main.park', verbose_name='Park')),
            ],
        ),
        migrations.AddField(
            model_name='pricetype',
            name='table',
            field=models.ForeignKey(db_column='PriceTable', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pricetable', verbose_name='Price Table'),
            preserve_default=False,
        ),
    ]
