# Generated by Django 4.0.6 on 2022-07-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_pricetype_deadline_pricetable_pricetype_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together={('minutes', 'hours', 'table', 'type')},
        ),
        migrations.RemoveField(
            model_name='pricetype',
            name='park',
        ),
    ]
