# Generated by Django 4.0.6 on 2022-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_pricetype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='is_archived',
            field=models.BooleanField(db_column='IsArchived', default=False, verbose_name='Is Archived'),
        ),
    ]
