# Generated by Django 4.0.6 on 2022-07-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_park_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetable',
            name='arquived',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='arquived',
        ),
        migrations.AddField(
            model_name='pricetable',
            name='archived',
            field=models.BooleanField(db_column='Archived', default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='archived',
            field=models.BooleanField(db_column='Archived', default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='park',
            name='is_archived',
            field=models.BooleanField(db_column='IsArchived', default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='park',
            name='is_open',
            field=models.BooleanField(db_column='IsOpen', default=False, verbose_name='Open'),
        ),
    ]
