# Generated by Django 4.0.6 on 2022-07-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_zone_is_archived_zone_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_archived',
            field=models.BooleanField(db_column='IsArchived', default=False, verbose_name='Archived'),
        ),
    ]
