# Generated by Django 4.0.6 on 2022-07-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_parkingspot_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(db_column='Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('park', 'name')},
        ),
    ]
