# Generated by Django 4.0.6 on 2022-07-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_zone_name_alter_zone_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='lugarid',
            field=models.ForeignKey(db_column='LugarID', on_delete=django.db.models.deletion.CASCADE, to='main.parkingspot'),
        ),
    ]
