# Generated by Django 4.0.6 on 2022-07-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_contrato_lugarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='is_open',
            field=models.BooleanField(db_column='IsOpen', default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_open',
            field=models.BooleanField(db_column='IsOpen', default=True, verbose_name='Open'),
        ),
    ]
