# Generated by Django 4.0.6 on 2022-07-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_park_is_open_alter_zone_is_open'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('park', 'name', 'is_archived')},
        ),
    ]
