# Generated by Django 4.0.6 on 2022-07-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_zone_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('registration', 'foreign', 'client')},
        ),
    ]
