# Generated by Django 4.0.4 on 2022-06-06 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('parks', '0006_alter_parkingspot_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datavalidade', models.DateField(db_column='DataValidade')),
                ('valorcontrato', models.FloatField(db_column='ValorContrato')),
                ('datainicio', models.DateField(db_column='DataInicio')),
                ('matricula', models.CharField(db_column='Matricula', max_length=8)),
                ('criadoem', models.DateTimeField(db_column='CriadoEm')),
                ('editadoem', models.DateTimeField(db_column='EditadoEm')),
            ],
            options={
                'db_table': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='EntradasSaidas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('matriculaviatura', models.ForeignKey(db_column='MatriculaViatura', on_delete=django.db.models.deletion.DO_NOTHING, to='main.car')),
            ],
            options={
                'db_table': 'Entradas/Saidas',
            },
        ),
        migrations.CreateModel(
            name='Estadoreserva',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=15, unique=True)),
            ],
            options={
                'db_table': 'EstadoReserva',
            },
        ),
        migrations.CreateModel(
            name='Modalidadepagamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=15, unique=True)),
            ],
            options={
                'db_table': 'ModalidadePagamento',
            },
        ),
        migrations.CreateModel(
            name='Periocidade',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('start', models.DateTimeField(db_column='Start')),
                ('end', models.DateTimeField(blank=True, db_column='End', null=True)),
            ],
            options={
                'db_table': 'Periocidade',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('divida', models.FloatField(blank=True, db_column='Divida', null=True)),
                ('preco', models.FloatField(blank=True, db_column='Preco', null=True)),
                ('criadoem', models.DateTimeField(db_column='CriadoEm', default=django.utils.timezone.now)),
                ('editadoem', models.DateTimeField(db_column='EditadoEm', default=django.utils.timezone.now)),
                ('contratoid', models.ForeignKey(blank=True, db_column='ContratoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.contrato')),
                ('entradassaidasid', models.ForeignKey(blank=True, db_column='entradassaidasID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.entradassaidas')),
                ('estadoreservaid', models.ForeignKey(db_column='EstadoReservaID', on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.estadoreserva')),
                ('lugarid', models.ForeignKey(db_column='LugarID', on_delete=django.db.models.deletion.DO_NOTHING, to='parks.parkingspot')),
                ('matricula', models.ForeignKey(db_column='matricula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.car')),
                ('parqueid', models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.DO_NOTHING, to='parks.park')),
                ('periocidadeid', models.ForeignKey(blank=True, db_column='PeriocidadeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.periocidade')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
        migrations.AddField(
            model_name='entradassaidas',
            name='periocidadeid',
            field=models.ForeignKey(db_column='PeriocidadeID', on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.periocidade'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modalidadepagamentoid',
            field=models.ForeignKey(db_column='ModalidadePagamentoID', on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.modalidadepagamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='parqueid',
            field=models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.DO_NOTHING, to='parks.park'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='zonaid',
            field=models.ForeignKey(db_column='ZonaID', on_delete=django.db.models.deletion.CASCADE, to='parks.zone'),
        ),
    ]
