# Generated by Django 4.0.4 on 2022-06-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadocontrato',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'EstadoContrato',
            },
        ),
        migrations.CreateModel(
            name='FacturaRecibo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('multa', models.TextField(blank=True, db_column='Multa', null=True)),
                ('precores', models.FloatField(db_column='PrecoRes')),
                ('emitidaem', models.DateTimeField(db_column='EmitidaEm')),
                ('contribuinte', models.TextField(db_column='Contribuinte', null=True)),
                ('comprovativopagamento', models.FileField(db_column='Comprovativo', upload_to='')),
                ('contratoid', models.ForeignKey(blank=True, db_column='ContratoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.contrato')),
                ('entradasaidaid', models.ForeignKey(blank=True, db_column='EntradaSaidaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.entradassaidas')),
                ('estadofaturaid', models.ForeignKey(db_column='EstadoFaturaID', on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.estadocontrato')),
                ('periocidadeid', models.ForeignKey(db_column='PeriocidadeID', on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.periocidade')),
                ('reservaid', models.ForeignKey(blank=True, db_column='ReservaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.reserva')),
            ],
            options={
                'db_table': 'Factura/Recibo',
            },
        ),
    ]
